version: "3"
services:
  segment-and-track-anything:
    image: nekanat/segment-and-track-anything-full:latest
    environment:
      - "DISPLAY=${DISPLAY}"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    volumes:
      - ./:/workspace
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    tty: true
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
